### ISSUE TITLE
vigil-local getting a 404 on the endpoint url

### ISSUE THREAD

**Issue by kennyparsons** [valeriansaliou/vigil-local#2]
I am currently running vigil (docker) v 1.22.1 and the latest vigil-local (arm). When starting the vigil local, I get the following error:
```
(DEBUG) - could not report to probe url: https://status.mydomain-here.com/reporter/internal/gateway/ (got status code: 404)
```

Indeed, this URL does not exists. But I dont see any info on how to set this up on the vigil "master" server showing my current polls.

**Comment by valeriansaliou** [comment]
Hello there! You should configure the service ID and node ID in Vigil's configuration, and restart Vigil.

As such: https://github.com/valeriansaliou/vigil/blob/master/config.cfg#L210

Also make sure that the `mode` is set to `local`, otherwise `vigil-local` reports will be rejected.
